###############################################################################
#
# Infrastructure Project
#
# File:
#   configs/traefik/dynamic/internal-services.yml
#
# Description:
#   Internal Traefik services and routers.
#
###############################################################################

http:

  routers:

    #
    # Traefik Dashboard
    #
    traefik-dashboard:

      entryPoints:

        - admin

    tls:

      options: default

      rule: >
        PathPrefix(`/api`)
        || PathPrefix(`/dashboard`)

      service: api@internal

      middlewares:

        - default-chain

        #
        # Enable after creating credentials.
        #
        # - auth-basic

      priority: 100