###############################################################################
#
# Infrastructure Project
#
###############################################################################

http:

  middlewares:

    wireguard-only:

      ipAllowList:

        sourceRange:

          - "10.100.100.0/24"