###############################################################################
#
# Infrastructure Project
#
# File:
#   configs/traefik/dynamic/redirect.yml
#
###############################################################################

http:

  middlewares:

    redirect-to-https:

      redirectScheme:

        scheme: https
        permanent: true