###############################################################################
#
# Infrastructure Project
#
# File:
#   configs/traefik/traefik.yml
#
# Description:
#   Static Traefik configuration
#
###############################################################################

global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true

ping: {}

log:
  level: INFO

accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100

providers:

  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: bridge-moje

  file:
    directory: /etc/traefik/dynamic
    watch: true

entryPoints:

  web:
    address: ":80"

  websecure:
    address: ":443"

  traefik:
    address: ":8080"

  prometheus:
    address: ":9090"

  alertmanager:
    address: ":9093"

certificatesResolvers:

  letsencrypt:

    acme:

      email: your@email.cz

      storage: /etc/traefik/acme/acme.json

      httpChallenge:

        entryPoint: web

metrics:

  prometheus:

    addEntryPointsLabels: true

    addRoutersLabels: true

    addServicesLabels: true