###############################################################################
#
# Infrastructure Project
#
# File:
#   configs/traefik/traefik.yml
#
# Description:
#   Static Traefik configuration
#
###############################################################################

###############################################################################
# Global
###############################################################################

global:

  #
  # Disable version check
  #

  checkNewVersion: false

  #
  # Disable anonymous telemetry
  #

  sendAnonymousUsage: false

###############################################################################
# API / Dashboard
###############################################################################

api:

  #
  # Enable dashboard
  #

  dashboard: true

  #
  # First startup only.
  #
  # Later:
  #
  # api:
  #   insecure: false
  #
  # Dashboard will be published through
  # a dedicated router protected
  # by BasicAuth.
  #

  insecure: false

###############################################################################
# Ping
###############################################################################

ping: {}

###############################################################################
# EntryPoints
###############################################################################

entryPoints:

  ###########################################################################
  # HTTP
  ###########################################################################

  web:

    address: ":80"

  ###########################################################################
  # HTTPS
  ###########################################################################

  websecure:

    address: ":443"

  ###########################################################################
  # Administration (WireGuard only)
  ###########################################################################

  admin:
    address: ":8443"

###############################################################################
# Providers
###############################################################################

providers:

  ###########################################################################
  # Docker Provider
  ###########################################################################

  docker:

    endpoint: "unix:///var/run/docker.sock"

    exposedByDefault: false

  ###########################################################################
  # File Provider
  ###########################################################################

  file:

    directory: /etc/traefik/dynamic

    watch: true

###############################################################################
# Logging
###############################################################################

log:

  level: DEBUG

  filePath: /var/log/traefik/traefik.log

###############################################################################
# Access Log
###############################################################################

accessLog:

  filePath: /var/log/traefik/access.log