###############################################################################
#
# Infrastructure Project
#
# File:
#   compose/10-traefik.yml
#
# Description:
#   Traefik v3 Reverse Proxy
#
###############################################################################

services:

  traefik:

    image: traefik:${TRAEFIK_VERSION}

    hostname: traefik

    restart: unless-stopped

    env_file:
      - .env

    command:
      - --configFile=/etc/traefik/traefik.yml

    networks:

      bridge-moje:
        ipv4_address: ${IP_TRAEFIK}

      traefik-moje:
        ipv4_address: ${IP_TRAEFIK_PUBLIC}

    ports:

      - "80:80"
      - "443:443"

      # Administration
      - "8080:8080"   # Dashboard
      - "8081:8081"   # Grafana
      - "8082:8082"   # Prometheus
      - "8083:8083"   # Alertmanager
      - "8084:8084"   # CrowdSec
      - "8085:8085"   # Loki
      - "8086:8086"   # Metabase

    volumes:

      - /var/run/docker.sock:/var/run/docker.sock:ro

      - ./configs/traefik/traefik.yml:/etc/traefik/traefik.yml:ro

      - ./configs/traefik/dynamic:/etc/traefik/dynamic:ro

      - ${INFRASTRUCTURE_DATA}/traefik/acme:/etc/traefik/acme

      - ${INFRASTRUCTURE_DATA}/traefik/logs:/var/log/traefik

    security_opt:

      - no-new-privileges:true

    healthcheck:

      test:
        - CMD
        - traefik
        - healthcheck
        - --ping

      interval: 30s

      timeout: 5s

      retries: 3

      start_period: 10s

    logging:

      driver: json-file

      options:

        max-size: ${LOG_MAX_SIZE}

        max-file: "${LOG_MAX_FILES}"

    labels:

      - traefik.enable=true