###############################################################################
#
# Infrastructure Project
#
# File:
#   compose/20-crowdsec.yml
#
# Description:
#   CrowdSec Security Engine
#
###############################################################################

services:

  ###########################################################################
  # CrowdSec
  ###########################################################################

  crowdsec:

    image: crowdsecurity/crowdsec:${CROWDSEC_VERSION}

    container_name: crowdsec

    restart: unless-stopped

    init: true

    networks:

      infrastructure:

        ipv4_address: ${IP_CROWDSEC}

    environment:

      TZ: ${TZ}

    volumes:

      #
      # Configuration
      #

      - ${CROWDSEC_DIR}/config:/etc/crowdsec

      #
      # Database
      #

      - ${CROWDSEC_DIR}/db:/var/lib/crowdsec/db

      #
      # Runtime data
      #

      - ${CROWDSEC_DIR}/data:/var/lib/crowdsec/data

      #
      # Traefik logs
      #

      - ${TRAEFIK_DIR}/logs:/logs:ro

      #
      # Docker socket
      #

      - /var/run/docker.sock:/var/run/docker.sock:ro

    healthcheck:

      test:

        - CMD

        - cscli

        - version

      interval: 30s

      timeout: 10s

      retries: 5

    security_opt:

      - no-new-privileges:true

    labels:

      - "com.centurylinklabs.watchtower.enable=true"